[package]
name = "ai"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rand_distr = "0.4.0"
colored = "2"

[[example]]
name = "mnist_digits"
path = "examples/mnist_handwritten_digits.rs"

[[example]]
name = "mnist_conv_digits"
path = "examples/mnist_conv_digits.rs"